import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  apiSidebar: [{ type: "autogenerated", dirName: "." }],
  docsSidebar: [{ type: "autogenerated", dirName: "." }],
  internalSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
